KIT ;
  IDL VERSION 1.2.8 ;
  TITLE 'Выработать рекомендации' ;
  AUTHOR 'Разработчик' ;
  CREATION DATE 3/6/96 ;
  PROJECT NAME 'Острые токсические поражения печени и почек' ;

  MODEL 'Нефро- и гепатопатия'
    {LWI
    F 0 -13 0 0 0 400
      0 0 0 0 3 2 1 34
      100 'Arial'
    F 1 -17 0 0 0 400
      0 0 0 204 3 2 1 49
      100 'Courier New'
    F 2 -27 0 0 0 400
      0 0 0 204 3 2 1 34
      160 'Arial'
    F 3 -17 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 4 -17 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 5 -19 0 0 0 400
      0 0 0 0 3 2 1 34
      140 'Arial'
    F 6 -24 0 0 0 400
      0 0 0 0 3 2 1 34
      180 'Arial'
    F 7 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Arial'
    F 8 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Arial'
    F 9 -17 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 10 -18 0 0 0 400
      0 0 0 204 3 2 1 34
      110 'Arial'
    F 11 -23 0 0 0 400
      0 0 0 204 3 2 1 34
      140 'Arial'
    D 2 3 3 7 10 7 7 7 1
    G 7 11
    E 'АИС обеспечивает врача отделения реанимации и интенсивной терапии возмо
жностями дифференциальной диагностики и обоснованного выбора тактики лечения б
ольных с острыми токсическими поражениями печени и почек. Рассматриваемые сист
емой возможные факторы токсического поражения: лекарственные препараты, технич
еские жидкости (ингаляционные и пероральные пути поступления), ядовитые и усло
вно съедобные грибы), а также хирургическую патологию (панкреатит, перитонит) 
и шок. '
    S 'Сеанс работы АИС следует общей схеме проведения консультации врачом-спе
циалистом, котрый на основе информации о больном (данные клинического наблюден
ия, результаты лабораторных и инструментальных исследований и т.п.) ставит раз
вернутый диагноз и назначает адекватное состоянию больного этиопатогенетическо
е лечение.'
    V 'Модель разрабатывается с точки зрения разработчика программного обеспеч
ения.'
    P 'Функциональная модель АИС разрабатывается как техническое задание на пр
ограммирование и ее декомпозиция обеспечивает точность, достаточную для описан
ия алгоритмов процедур и объектов программы.'
    O 'Источником знаний для разработки функциональной модели являются: литера
турные сведения по диагностике и лечению нефро- и гепатопатии, опыт лечения бо
льных в институте скорой помощи им. Н.В.Склифосовского.'
    T 'WORKING'
    R 34
    B 1 18 15
      0 1 -1 1 0 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выработать рекомендации'
       'WORKING'
      1 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Поставить диагноз'
       'Определение развернутого диагноза по анамнестическим данным, клиническ
им наблюдениям, лабораторным и инструментальным исследованиям'
       'WORKING'
      2 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выработать<CR>показания'
       'Формирование списка показанных методов лечения с указанием их эффектив
ности по развернутому диагнозу'
       'WORKING'
      3 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Определить<CR>противопоказания'
       'Программный элемент по развернутому диагнозу, включающему осложнения и
 сопутствующие заболевания, определяет список противопоказанных данному больно
му методов лечения'
       'WORKING'
      4 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Оптимизировать<CR>лечение'
       'Определение списка рекомендаций, ранжированного по степени эффективнос
ти методов'
       'WORKING'
      5 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Определить<CR>наличие ОППН'
       'определение наличия острой песеночно-почечной патологии'
       'WORKING'
      6 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Установить<CR>этиологию'
       'Из явного ответа пользователя или уточняющего диалога определяется эти
ология заболевания'
       'WORKING'
      7 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Установить<CR>патогенез'
       'Определение степеней основных нарушений и осложнений'
       'WORKING'
      8 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Определить<CR>сопутствующие<CR>заболевания'
       'Определение сопутствующих заболеваний'
       'WORKING'
      9 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Сформулировать<CR>диагноз'
       'Формулировка развернутого диагноза, включающего этипатогенез заболеван
ия, степени основных нарушений, осложнения и сопутствующие заболевания'
       'WORKING'
      10 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выбрать<CR>детоксикационные<CR>методы'
       'Выбор эффективных для данного пациента консервативных и активных метод
ов лечения ОППН'
       'WORKING'
      11 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выбрать<CR>коррегирующие<CR>и стабилизирующие<CR>методы лечения'
       'Выбираются методы коррекции гомеостаза, гемостаза и т.п.'
       'WORKING'
      12 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выбрать<CR>методы<CR>симптоматического<CR>лечения'
       'Определениеэффективного набора методов симптоматического лечения'
       'WORKING'
      13 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Выбрать<CR>методы<CR>антибактериального<CR>лечения<CR>'
       'Определение набора методов антибактериального лечения'
       'WORKING'
      14 1 -1 1 1 0 0 0 1 0.000000 1.000000
      255 255 255
       'Сформировать<CR>список показаний'
       'Формирование списка показаний, т.е. методов детоксикационного, корриги
рующего, симптоматического и антибактериального лечения с указанием их эффекти
вности для данного больного'
       'WORKING'
      15 0 0 0 0 0 0 0 0.0 0.0
      255 255 255
      16 0 0 0 0 0 0 0 0.0 0.0
      255 255 255
      17 0 0 0 0 0 0 0 0.0 0.0
      255 255 255
    B 2 42 38
      0 1 -1 1 1 0 1
      255 255
       'Знания о терапии'
       'Сведения о показанных методах и оценки их эффективности'
       'WORKING'
      1 1 -1 1 1 0 1
      255 255
       'Рекомендации'
       'Выработанные АИС рекомендации по лечению'
       'WORKING'
      2 1 -1 1 1 0 1
      255 255
       'Программа'
       'Основная программа системы'
       'PUBLICATION'
      3 1 -1 1 1 0 1
      255 255
       'Данные о больном'
       'Совокупность сведений о больном (анамнез, клинические данные, результа
ты исследований)'
       'WORKING'
      4 1 -1 1 1 0 1
      255 255
       'Сочетаемость методов'
       'Литературные и экспертные знания и опыт о сочетаемости методов лечения
'
       'WORKING'
      5 1 -1 1 1 0 1
      255 255
       'Противопоказания'
       'Список противопоказанных методов для данного набора нарушений, с указа
нием степени опасности'
       'WORKING'
      6 1 -1 1 1 0 1
      255 255
       'Показания'
       'Список показаний с оценками эффективности методов для данного набора н
арушений'
       'WORKING'
      7 1 -1 1 0 0 1
      255 255
       'Медицинские знания'
       'WORKING'
      8 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Отбор методов"'
       'Подпрограмма отбора наиболее эффективно компенсирующих нарушения и без
опасных методов'
       'WORKING'
      9 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Противопоказания"'
       'Подпрограмма отбора противопоказанных данному больному методов лечения
'
       'WORKING'
      10 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Показания"'
       'Подпрограмма отбора показанных данному больному методов лечения с указ
анием их эффективности'
       'WORKING'
      11 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Диагноз"'
       'Подпрограмма определения развернутого диагноза'
       'WORKING'
      12 1 -1 1 1 0 1
      255 255
       'Диагноз'
       'Развернутый диагноз, включающий этиопричину, осложнения, сопутствующие
 заболевания и указывающий степени основных нарушений'
       'PUBLICATION'
      13 1 -1 1 1 0 1
      255 255
       '"Наш больной"'
       'У больного есть нефро- или гепатопатия'
       'WORKING'
      14 1 -1 1 0 0 1
      255 255
       'ОППН'
       'WORKING'
      15 1 -1 1 1 0 1
      255 255
       '"Не наш больной (1)"'
       'У данного больного нет острой почеченой или печеночной патологии'
       'WORKING'
      16 1 -1 1 1 0 1
      255 255
       '"Не наш больной (2)"'
       'У данного больного острая почеченая или печеночная патология вызвана н
е рассматриваемой в программе этиопричиной'
       'WORKING'
      17 1 -1 1 1 0 1
      255 255
       'Симптомы ОППН'
       'Симптомы и признаки острой печеночно-почечной недостаточности'
       'WORKING'
      18 1 -1 1 1 0 1
      255 255
       'Anamnesis morbi'
       'Совокупность сведений об анамнезе заболевания'
       'WORKING'
      19 1 -1 1 1 0 1
      255 255
       'Состояние систем'
       'Состояние систем организма - совокупность сведений о больном (клиничес
кие данные, результаты исследований)'
       'WORKING'
      20 1 -1 1 1 0 1
      255 255
       'Anamnesis vitae'
       'Совокупность сведений об анамнезе жизни'
       'WORKING'
      21 1 -1 1 1 0 1
      255 255
       'Этиология'
       'Этиология острой почеченой и/или печеночной патологии'
       'WORKING'
      22 1 -1 1 1 0 1
      255 255
       'Патогенез'
       'Патогенез заболевания - степени основных нарушений, осложнения'
       'PUBLICATION'
      23 1 -1 1 1 0 1
      255 255
       'Сопутствующие заболевания'
       'Список сопутствующих заболеваний'
       'WORKING'
      24 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Анамнез жизни"'
       'Подпрограмма ввода сведений о  сопутствующих заболеваниях и об особенн
остях течения болезни'
       'WORKING'
      25 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Патогенез"'
       'Подпрограмма определения степени основных нарушений, состояния систем 
организма, осложнений'
       'WORKING'
      26 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Наличие ОППН"'
       'Подпрограмма определения наличия ОППН у данного больного'
       'WORKING'
      27 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Этиология"'
       'Подпрограмма определения этиопричины заболевания'
       'WORKING'
      28 1 -1 1 1 0 1
      255 255
       'Знания о противопоказаниях'
       'Сведения о противопоказаниях и степени опасности применения методов'
       'WORKING'
      29 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Детоксикация"'
       'Подпрограмма выбора показанных данному больному детоксикационных метод
ов лечения'
       'WORKING'
      30 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Коррекция"'
       'Подпрограмма выбора показанных данному больному коррегирующих и стабил
изирующих методов лечения'
       'WORKING'
      31 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Симптоматическое лечение"'
       'Подпрограмма выбора показанных данному больному симптоматических метод
ов лечения'
       'WORKING'
      32 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Антибактериальное лечение"'
       'Подпрограмма выбора показанных данному больному антибактериальных мето
дов'
       'WORKING'
      33 1 -1 1 1 0 1
      255 255
       'Подпрограмма "Список показаний"'
       'Подпрограмма формирования списка показанных данному больному методов л
ечения с указанием их эффективности'
       'WORKING'
      34 1 -1 1 1 0 1
      255 255
       'Детоксикационные методы'
       'Список показанных больному детоксикационных методов'
       'PUBLICATION'
      35 1 -1 1 1 0 1
      255 255
       'Корригирующие методы'
       'Список показанных данному больному корригирующих и стабилизирующих мет
одов'
       'WORKING'
      36 1 -1 1 1 0 1
      255 255
       'Симптоматическое лечение'
       'Список показанных данному больному симптоматических методов лечения'
       'PUBLICATION'
      37 1 -1 1 1 0 1
      255 255
       'Антибактериальное лечение'
       'Список показанных данному больному методов антибактериального лечения'

       'WORKING'
      38 0 0 0 0 0 0
      255 255
      39 0 0 0 0 0 0
      255 255
      40 0 0 0 0 0 0
      255 255
      41 0 0 0 0 0 0
      255 255
    W ffffffff ffffffff ffffffff ffffffff
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    M 0  }
 ;
    AUTHOR 'Разработчик' ;
    PROJECT NAME 'Острые токсические поражения печени и почек' ;

    DIAGRAM GRAPHIC A-0 ;
      CREATION DATE 3/6/96 ;
      REVISION DATE 4/6/96 ;
      TITLE 'Выработать рекомендации' ;
      STATUS WORKING ;

      BOX 0 ;
        NAME '{LWI I 2 255 255 255}Выработать рекомендации' ;
        BOX COORDINATES (0.33173,0.65831) (0.66346,0.32915) ;
        DETAIL REFERENCE N A0 ;
      ENDBOX ;

      ARROWSEG 1 ;
        SOURCE BORDER ;
        PATH (0.01923,0.47806) (0.33173,0.47806) ;
        LABEL '{LWI I 9 255 255 }Данные о больном' ;
        LABEL COORDINATES (0.01923,0.47022) ;
        SINK BOX 0I1 ;
      ENDSEG ;

      ARROWSEG 4 ;
        SOURCE BOX 0O1 ;
        PATH (0.66346,0.47806) (0.97596,0.47806) ;
        LABEL '{LWI I 9 255 255 }Рекомендации' ;
        LABEL COORDINATES (0.83173,0.47022) ;
        SINK BORDER ;
      ENDSEG ;

      ARROWSEG 3 ;
        SOURCE BORDER ;
        PATH (0.49519,0.96395) (0.49519,0.65831) ;
        LABEL '{LWI I 9 255 255 }Программа' ;
        LABEL COORDINATES (0.50769,0.93887) ;
        SINK BOX 0M1 ;
      ENDSEG ;

      ARROWSEG 5 ;
        SOURCE BORDER ;
        PATH (0.50000,0.03135) (0.50000,0.32915) ;
        LABEL '{LWI I 9 255 255 }Медицинские<CR>знания' ;
        LABEL COORDINATES (0.50865,0.16144) ;
        SINK BOX 0C1 ;
      ENDSEG ;

    ENDDIAGRAM ;

    DIAGRAM GRAPHIC A0 ;
      CREATION DATE 3/6/96 ;
      REVISION DATE 5/6/96 ;
      TITLE 'Выработать рекомендации' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 9 255 255 255}Поставить диагноз' ;
        BOX COORDINATES (0.11058,0.31348) (0.28846,0.20376) ;
        DETAIL REFERENCE N A1 ;
      ENDBOX ;

      BOX 2 ;
        NAME '{LWI I 3 255 255 255}Выработать<CR>показания' ;
        BOX COORDINATES (0.37019,0.47022) (0.57692,0.36050) ;
        DETAIL REFERENCE N A2 ;
      ENDBOX ;

      BOX 3 ;
        NAME '{LWI I 3 255 255 255}Определить<CR>противопоказания' ;
        BOX COORDINATES (0.39904,0.68966) (0.61538,0.57994) ;
        DETAIL REFERENCE N A3 ;
      ENDBOX ;

      BOX 4 ;
        NAME '{LWI I 3 255 255 255}Оптимизировать<CR>лечение' ;
        BOX COORDINATES (0.68750,0.48589) (0.87500,0.34483) ;
        DETAIL REFERENCE N A4 ;
      ENDBOX ;

      ARROWSEG 10 ;
        SOURCE BRANCH 11 ;
        PATH (0.44231,0.10972) (0.19712,0.10972) (0.19712,0.20376) ;
        SINK BOX 1C1 ;
      ENDSEG ;

      ARROWSEG 11 ;
        SOURCE BRANCH 1 ;
        PATH (0.50000,0.10972) (0.44231,0.10972) ;
        LABEL '{LWI I 7 255 255 }ОППН' ;
        LABEL COORDINATES (0.31442,0.09561) ;
        SINK BRANCH 10 15 ;
      ENDSEG ;

      ARROWSEG 12 ;
        SOURCE BRANCH 1 ;
        PATH (0.50000,0.10972) (0.59615,0.10972) ;
        SINK BRANCH 13 14 ;
      ENDSEG ;

      ARROWSEG 13 ;
        SOURCE BRANCH 12 ;
        PATH (0.59615,0.10972) (0.78846,0.10972) (0.78846,0.34483) ;
        LABEL '{LWI I 7 255 255 }Сочетаемость методов' ;
        LABEL COORDINATES (0.64712,0.10502) ;
        SINK BOX 4C1 ;
      ENDSEG ;

      ARROWSEG 5 ;
        SOURCE TUNNEL  {LWI Q}BOX 1O1 ;
        PATH (0.28846,0.25862) (0.33173,0.25862) (0.33173,0.42320) ;
        LABEL '{LWI I 7 255 255 }Диагноз' ;
        LABEL COORDINATES (0.29808,0.25392) ;
        SINK BRANCH 7 6 ;
      ENDSEG ;

      ARROWSEG 3 ;
        SOURCE BORDER I1 (0.00481,0.26646) ;
        PATH (0.01923,0.25862) (0.11058,0.25862) ;
        LABEL '{LWI I 7 255 255 }Данные о<CR>больном' ;
        LABEL COORDINATES (0.01538,0.21003) ;
        SINK BOX 1I1 ;
      ENDSEG ;

      ARROWSEG 8 ;
        SOURCE BOX 2O1 ;
        PATH (0.57692,0.41536) (0.68750,0.41536) ;
        LABEL '{LWI I 7 255 255 }Показания' ;
        LABEL COORDINATES (0.61154,0.41066) ;
        SINK BOX 4I1 ;
      ENDSEG ;

      ARROWSEG 4 ;
        SOURCE BOX 4O1 ;
        PATH (0.87500,0.41536) (0.97596,0.41536) ;
        LABEL '{LWI I 4 255 255 }Рекомендации' ;
        LABEL COORDINATES (0.87692,0.40909) ;
        SINK BORDER O1 (0.97885,0.42320) ;
      ENDSEG ;

      ARROWSEG 6 ;
        SOURCE BRANCH 5 ;
        PATH (0.33173,0.42320) (0.37019,0.42320) ;
        SINK BOX 2I1 ;
      ENDSEG ;

      ARROWSEG 17 ;
        SOURCE BRANCH 18 ;
        PATH (0.19712,0.54859) (0.48558,0.54859) (0.48558,0.47022) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Показания"' ;
        LABEL COORDINATES (0.35192,0.51881) ;
        SINK BOX 2M1 ;
      ENDSEG ;

      ARROWSEG 9 ;
        SOURCE BOX 3O1 ;
        PATH (0.61538,0.63480) (0.63942,0.63480) (0.63942,0.43103) (0.68750,0.
43103) ;
        LABEL '{LWI I 7 255 255 }Противопоказания' ;
        LABEL COORDINATES (0.64327,0.60658) ;
        SINK BOX 4I2 ;
      ENDSEG ;

      ARROWSEG 19 ;
        SOURCE BRANCH 20 ;
        PATH (0.19712,0.72884) (0.52404,0.72884) (0.52404,0.68966) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Противопоказания"' ;
        LABEL COORDINATES (0.24904,0.70063) ;
        SINK BOX 3M1 ;
      ENDSEG ;

      ARROWSEG 21 ;
        SOURCE BRANCH 2 ;
        PATH (0.19712,0.86207) (0.79327,0.86207) (0.79327,0.48589) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма "Отбор методов"' ;
        LABEL COORDINATES (0.54615,0.85893) ;
        SINK BOX 4M1 ;
      ENDSEG ;

      ARROWSEG 18 ;
        SOURCE BRANCH 20 ;
        PATH (0.19712,0.72884) (0.19712,0.54859) ;
        SINK BRANCH 16 17 ;
      ENDSEG ;

      ARROWSEG 20 ;
        SOURCE BRANCH 2 ;
        PATH (0.19712,0.86207) (0.19712,0.72884) ;
        SINK BRANCH 18 19 ;
      ENDSEG ;

      ARROWSEG 2 ;
        SOURCE BORDER M1 (0.18750,0.98433) ;
        PATH (0.19712,0.96395) (0.19712,0.86207) ;
        LABEL '{LWI I 4 255 255 }Программа' ;
        LABEL COORDINATES (0.20288,0.96708) ;
        SINK BRANCH 20 21 ;
      ENDSEG ;

      ARROWSEG 16 ;
        SOURCE BRANCH 18 ;
        PATH (0.19712,0.54859) (0.19712,0.31348) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Диагноз"' ;
        LABEL COORDINATES (0.10288,0.40125) ;
        SINK BOX 1M1 ;
      ENDSEG ;

      ARROWSEG 7 ;
        SOURCE BRANCH 5 ;
        PATH (0.33173,0.42320) (0.33173,0.63480) (0.39904,0.63480) ;
        SINK BOX 3I1 ;
      ENDSEG ;

      ARROWSEG 15 ;
        SOURCE BRANCH 11 ;
        PATH (0.44231,0.10972) (0.44231,0.36050) ;
        LABEL '{LWI I 7 255 255 }Знания о<CR>терапии' ;
        LABEL COORDINATES (0.45288,0.23824) ;
        SINK BOX 2C1 ;
      ENDSEG ;

      ARROWSEG 1 ;
        SOURCE BORDER C1 (0.49038,0.02665) ;
        PATH (0.50000,0.03135) (0.50000,0.10972) ;
        LABEL '{LWI I 7 255 255 }Медицинские<CR>знания' ;
        LABEL COORDINATES (0.50577,0.05329) ;
        SINK BRANCH 11 12 ;
      ENDSEG ;

      ARROWSEG 14 ;
        SOURCE BRANCH 12 ;
        PATH (0.59615,0.10972) (0.59615,0.57994) ;
        LABEL '{LWI I 7 255 255 }Знания о<CR>противопоказаниях' ;
        LABEL COORDINATES (0.60000,0.24138) ;
        SINK BOX 3C1 ;
      ENDSEG ;

    ENDDIAGRAM ;

    DIAGRAM GRAPHIC A1 ;
      CREATION DATE 4/6/96 ;
      REVISION DATE 13/6/96 ;
      TITLE 'Поставить диагноз' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 3 255 255 255}Определить<CR>наличие ОППН' ;
        BOX COORDINATES (0.13942,0.31348) (0.28365,0.19592) ;
        DETAIL REFERENCE N A1 ;
      ENDBOX ;

      BOX 2 ;
        NAME '{LWI I 3 255 255 255}Установить<CR>этиологию' ;
        BOX COORDINATES (0.32692,0.47022) (0.47115,0.35266) ;
        DETAIL REFERENCE N A2 ;
      ENDBOX ;

      BOX 3 ;
        NAME '{LWI I 3 255 255 255}Определить<CR>сопутствующие<CR>заболевания'
 ;
        BOX COORDINATES (0.56731,0.78370) (0.71154,0.66614) ;
        DETAIL REFERENCE N A3 ;
      ENDBOX ;

      BOX 4 ;
        NAME '{LWI I 3 255 255 255}Установить<CR>патогенез' ;
        BOX COORDINATES (0.57212,0.61129) (0.70673,0.49373) ;
        DETAIL REFERENCE N A4 ;
      ENDBOX ;

      BOX 5 ;
        NAME '{LWI I 3 255 255 255}Сформулировать<CR>диагноз' ;
        BOX COORDINATES (0.76442,0.59561) (0.90865,0.49373) ;
        DETAIL REFERENCE N A5 ;
      ENDBOX ;

      ARROWSEG 23 ;
        SOURCE BRANCH 2 ;
        PATH (0.40385,0.11755) (0.63942,0.11755) (0.63942,0.49373) ;
        SINK BOX 4C1 ;
      ENDSEG ;

      ARROWSEG 24 ;
        SOURCE BRANCH 2 ;
        PATH (0.40385,0.11755) (0.20192,0.11755) (0.20192,0.19592) ;
        SINK BOX 1C1 ;
      ENDSEG ;

      ARROWSEG 7 ;
        SOURCE BRANCH 9 ;
        PATH (0.09615,0.25078) (0.10577,0.25078) ;
        SINK BRANCH 5 6 ;
      ENDSEG ;

      ARROWSEG 5 ;
        SOURCE BRANCH 7 ;
        PATH (0.10577,0.25078) (0.13942,0.25078) ;
        LABEL '{LWI I 7 255 255 }Симптомы ОППН' ;
        LABEL COORDINATES (0.04423,0.16301) ;
        SQUIGGLE COORDINATES (0.10769,0.17085) (0.12019,0.25078) ;
        SINK BOX 1I1 ;
      ENDSEG ;

      ARROWSEG 4 ;
        SOURCE BORDER I1 (0.00481,0.25862) ;
        PATH (0.01923,0.25078) (0.08654,0.25078) ;
        LABEL '{LWI I 7 255 255 }Данные о<CR>больном' ;
        LABEL COORDINATES (0.01635,0.27586) ;
        SINK BRANCH 9 10 ;
      ENDSEG ;

      ARROWSEG 9 ;
        SOURCE BRANCH 4 ;
        PATH (0.08654,0.25078) (0.09615,0.25078) ;
        SINK BRANCH 7 8 ;
      ENDSEG ;

      ARROWSEG 12 ;
        SOURCE BOX 1O1 ;
        PATH (0.28365,0.25078) (0.31250,0.25078) ;
        SINK BRANCH 20 21 ;
      ENDSEG ;

      ARROWSEG 20 ;
        SOURCE BRANCH 12 ;
        PATH (0.31250,0.25078) (0.94712,0.25078) (0.94712,0.41536) ;
        LABEL '{LWI I 7 255 255 }"Не наш больной (1)"' ;
        LABEL COORDINATES (0.68750,0.24295) ;
        SINK JOIN 31 ;
      ENDSEG ;

      ARROWSEG 13 ;
        SOURCE BOX 2O1 ;
        PATH (0.47115,0.41536) (0.54327,0.41536) ;
        LABEL '{LWI I 7 255 255 }Этиология' ;
        LABEL COORDINATES (0.49038,0.41379) ;
        SINK BRANCH 17 16 ;
      ENDSEG ;

      ARROWSEG 17 ;
        SOURCE BRANCH 13 ;
        PATH (0.54327,0.41536) (0.74519,0.41536) ;
        SINK BRANCH 30 32 ;
      ENDSEG ;

      ARROWSEG 30 ;
        SOURCE BRANCH 17 ;
        PATH (0.74519,0.41536) (0.94712,0.41536) ;
        LABEL '{LWI I 7 255 255 }"Не наш больной (2)"' ;
        LABEL COORDINATES (0.76346,0.40282) ;
        SINK JOIN 31 ;
      ENDSEG ;

      ARROWSEG 11 ;
        SOURCE JOIN 3 31 ;
        PATH (0.94712,0.53292) (0.97596,0.53292) ;
        LABEL '{LWI I 7 255 255 }Диагноз' ;
        LABEL COORDINATES (0.92788,0.57680) ;
        SINK TUNNEL  {LWI Q}BORDER ;
      ENDSEG ;

      ARROWSEG 14 ;
        SOURCE BRANCH 16 ;
        PATH (0.54327,0.53292) (0.57212,0.53292) ;
        SINK BOX 4I1 ;
      ENDSEG ;

      ARROWSEG 18 ;
        SOURCE BOX 4O1 ;
        PATH (0.70673,0.54075) (0.76442,0.54075) ;
        LABEL '{LWI I 7 255 255 }Патогенез' ;
        LABEL COORDINATES (0.67788,0.46395) ;
        SQUIGGLE COORDINATES (0.71538,0.47179) (0.72115,0.54075) ;
        SINK BOX 5I2 ;
      ENDSEG ;

      ARROWSEG 29 ;
        SOURCE BRANCH 25 ;
        PATH (0.40385,0.63480) (0.20192,0.63480) (0.20192,0.31348) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Наличие ОППН"' ;
        LABEL COORDINATES (0.25000,0.60815) ;
        SINK BOX 1M1 ;
      ENDSEG ;

      ARROWSEG 28 ;
        SOURCE BRANCH 25 ;
        PATH (0.40385,0.63480) (0.63942,0.63480) (0.63942,0.61129) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Патогенез"' ;
        LABEL COORDINATES (0.42981,0.58777) ;
        SQUIGGLE COORDINATES (0.47212,0.61442) (0.48558,0.63480) ;
        SINK BOX 4M1 ;
      ENDSEG ;

      ARROWSEG 19 ;
        SOURCE BOX 3O1 ;
        PATH (0.71154,0.72100) (0.72596,0.72100) (0.72596,0.57210) (0.76442,0.
57210) ;
        LABEL '{LWI I 7 255 255 }Сопутствующие<CR>заболевания' ;
        LABEL COORDINATES (0.73365,0.67085) ;
        SINK BOX 5I3 ;
      ENDSEG ;

      ARROWSEG 26 ;
        SOURCE BRANCH 1 ;
        PATH (0.40385,0.88558) (0.63942,0.88558) (0.63942,0.78370) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Анамнез жизни"' ;
        LABEL COORDINATES (0.50385,0.85423) ;
        SINK BOX 3M1 ;
      ENDSEG ;

      ARROWSEG 10 ;
        SOURCE BRANCH 4 ;
        PATH (0.08654,0.25078) (0.08654,0.73668) (0.56731,0.73668) ;
        LABEL '{LWI I 7 255 255 }Anamnesis<CR>vitae' ;
        LABEL COORDINATES (0.23462,0.68966) ;
        SQUIGGLE COORDINATES (0.26538,0.71630) (0.25481,0.73668) ;
        SINK BOX 3I2 ;
      ENDSEG ;

      ARROWSEG 8 ;
        SOURCE BRANCH 9 ;
        PATH (0.09615,0.25078) (0.09615,0.55643) (0.57212,0.55643) ;
        LABEL '{LWI I 7 255 255 }Состояние<CR>систем' ;
        LABEL COORDINATES (0.22115,0.47649) ;
        SQUIGGLE COORDINATES (0.26058,0.51567) (0.25000,0.55643) ;
        SINK BOX 4I2 ;
      ENDSEG ;

      ARROWSEG 6 ;
        SOURCE BRANCH 7 ;
        PATH (0.10577,0.25078) (0.10577,0.41536) (0.32692,0.41536) ;
        LABEL '{LWI I 7 255 255 }Anamnesis<CR>morbi' ;
        LABEL COORDINATES (0.22692,0.35737) ;
        SQUIGGLE COORDINATES (0.26538,0.39655) (0.25000,0.41536) ;
        SINK BOX 2I2 ;
      ENDSEG ;

      ARROWSEG 21 ;
        SOURCE BRANCH 12 ;
        PATH (0.31250,0.25078) (0.31250,0.39969) (0.32692,0.39969) ;
        LABEL '{LWI I 7 255 255 }Диагноз' ;
        LABEL COORDINATES (0.32019,0.32445) ;
        SINK BOX 2I1 ;
      ENDSEG ;

      ARROWSEG 2 ;
        SOURCE BORDER C1 (0.39423,0.02665) ;
        PATH (0.40385,0.03135) (0.40385,0.11755) ;
        LABEL '{LWI I 7 255 255 }ОППН' ;
        LABEL COORDINATES (0.41442,0.05643) ;
        SINK BRANCH 22 23 24 ;
      ENDSEG ;

      ARROWSEG 22 ;
        SOURCE BRANCH 2 ;
        PATH (0.40385,0.11755) (0.40385,0.35266) ;
        SINK BOX 2C1 ;
      ENDSEG ;

      ARROWSEG 27 ;
        SOURCE BRANCH 25 ;
        PATH (0.40385,0.63480) (0.40385,0.47022) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Этиология"' ;
        LABEL COORDINATES (0.43750,0.51254) ;
        SQUIGGLE COORDINATES (0.43750,0.50313) (0.40385,0.50157) ;
        SINK BOX 2M1 ;
      ENDSEG ;

      ARROWSEG 25 ;
        SOURCE BRANCH 1 ;
        PATH (0.40385,0.88558) (0.40385,0.63480) ;
        SINK BRANCH 27 29 28 ;
      ENDSEG ;

      ARROWSEG 1 ;
        SOURCE BORDER M1 (0.39423,0.98433) ;
        PATH (0.40385,0.96395) (0.40385,0.88558) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Диагноз"' ;
        LABEL COORDINATES (0.30673,0.94828) ;
        SINK BRANCH 25 26 ;
      ENDSEG ;

      ARROWSEG 16 ;
        SOURCE BRANCH 13 ;
        PATH (0.54327,0.41536) (0.54327,0.53292) ;
        SINK BRANCH 15 14 ;
      ENDSEG ;

      ARROWSEG 15 ;
        SOURCE BRANCH 16 ;
        PATH (0.54327,0.53292) (0.54327,0.70533) (0.56731,0.70533) ;
        SINK BOX 3I1 ;
      ENDSEG ;

      ARROWSEG 32 ;
        SOURCE BRANCH 17 ;
        PATH (0.74519,0.41536) (0.74519,0.50940) (0.76442,0.50940) ;
        SINK BOX 5I1 ;
      ENDSEG ;

      ARROWSEG 31 ;
        SOURCE JOIN 20 30 ;
        PATH (0.94712,0.41536) (0.94712,0.53292) ;
        SINK JOIN 11 ;
      ENDSEG ;

    ENDDIAGRAM ;

    DIAGRAM GRAPHIC A2 ;
      CREATION DATE 5/6/96 ;
      REVISION DATE 13/6/96 ;
      TITLE 'Выработать показания' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 3 255 255 255}Выбрать<CR>детоксикационные<CR>методы' ;
        BOX COORDINATES (0.17788,0.32132) (0.33654,0.18025) ;
        DETAIL REFERENCE N A1 ;
      ENDBOX ;

      BOX 2 ;
        NAME '{LWI I 3 255 255 255}Выбрать<CR>коррегирующие<CR>и стабилизирующ
ие<CR>методы лечения' ;
        BOX COORDINATES (0.27885,0.49373) (0.46635,0.33699) ;
        DETAIL REFERENCE N A2 ;
      ENDBOX ;

      BOX 3 ;
        NAME '{LWI I 3 255 255 255}Выбрать<CR>методы<CR>симптоматического<CR>л
ечения' ;
        BOX COORDINATES (0.39423,0.66614) (0.55288,0.50940) ;
        DETAIL REFERENCE N A3 ;
      ENDBOX ;

      BOX 4 ;
        NAME '{LWI I 3 255 255 255}Выбрать<CR>методы<CR>антибактериального<CR>
лечения<CR>' ;
        BOX COORDINATES (0.49038,0.85423) (0.66827,0.68182) ;
        DETAIL REFERENCE N A4 ;
      ENDBOX ;

      BOX 5 ;
        NAME '{LWI I 3 255 255 255}Сформировать<CR>список показаний' ;
        BOX COORDINATES (0.73558,0.57210) (0.90865,0.41536) ;
        DETAIL REFERENCE N A5 ;
      ENDBOX ;

      ARROWSEG 15 ;
        SOURCE BRANCH 1 ;
        PATH (0.37019,0.10972) (0.26442,0.10972) (0.26442,0.18025) ;
        SINK BOX 1C1 ;
      ENDSEG ;

      ARROWSEG 16 ;
        SOURCE BRANCH 1 ;
        PATH (0.37019,0.10972) (0.49519,0.10972) ;
        SINK BRANCH 17 18 ;
      ENDSEG ;

      ARROWSEG 17 ;
        SOURCE BRANCH 16 ;
        PATH (0.49519,0.10972) (0.61058,0.10972) (0.61058,0.68182) ;
        SINK BOX 4C1 ;
      ENDSEG ;

      ARROWSEG 5 ;
        SOURCE BOX 1O1 ;
        PATH (0.33654,0.25078) (0.56250,0.25078) (0.56250,0.46238) (0.73558,0.
46238) ;
        LABEL '{LWI I 7 255 255 }Детоксикационные<CR>методы' ;
        LABEL COORDINATES (0.37308,0.20219) ;
        SQUIGGLE COORDINATES (0.43750,0.22884) (0.46154,0.25078) ;
        SINK BOX 5I1 ;
      ENDSEG ;

      ARROWSEG 13 ;
        SOURCE BRANCH 10 ;
        PATH (0.13462,0.41536) (0.27885,0.41536) ;
        SINK BOX 2I1 ;
      ENDSEG ;

      ARROWSEG 6 ;
        SOURCE BOX 2O1 ;
        PATH (0.46635,0.42320) (0.54808,0.42320) (0.54808,0.48589) (0.73558,0.
48589) ;
        LABEL '{LWI I 7 255 255 }Корригирующие<CR>методы' ;
        LABEL COORDINATES (0.62019,0.38715) ;
        SQUIGGLE COORDINATES (0.66731,0.41379) (0.64423,0.48589) ;
        SINK BOX 5I2 ;
      ENDSEG ;

      ARROWSEG 3 ;
        SOURCE TUNNEL {LWI Q} BORDER;
        PATH (0.90865,0.49373) (0.97596,0.49373) ;
        LABEL '{LWI I 7 255 255 }Показания' ;
        LABEL COORDINATES (0.91346,0.49216) ;
        SINK BORDER O1 (0.97885,0.50157) ;
      ENDSEG ;

      ARROWSEG 7 ;
        SOURCE BOX 3O1 ;
        PATH (0.55288,0.58777) (0.64423,0.58777) (0.64423,0.51724) (0.73558,0.
51724) ;
        LABEL '{LWI I 7 255 255 }Симптоматическое<CR>лечение' ;
        LABEL COORDINATES (0.68654,0.32132) ;
        SQUIGGLE COORDINATES (0.74038,0.34796) (0.68750,0.51724) ;
        SINK BOX 5I3 ;
      ENDSEG ;

      ARROWSEG 4 ;
        SOURCE BORDER I1 (0.00481,0.59561) ;
        PATH (0.01923,0.58777) (0.13462,0.58777) ;
        LABEL '{LWI I 7 255 255 }Диагноз' ;
        LABEL COORDINATES (0.00962,0.58621) ;
        SINK BRANCH 9 10 11 ;
      ENDSEG ;

      ARROWSEG 9 ;
        SOURCE BRANCH 4 ;
        PATH (0.13462,0.58777) (0.39423,0.58777) ;
        SINK BOX 3I1 ;
      ENDSEG ;

      ARROWSEG 8 ;
        SOURCE BOX 4O1 ;
        PATH (0.66827,0.75235) (0.70192,0.75235) (0.70192,0.53292) (0.73558,0.
53292) ;
        LABEL '{LWI I 7 255 255 }Антибактериальное<CR>лечение' ;
        LABEL COORDINATES (0.70865,0.63480) ;
        SQUIGGLE COORDINATES (0.73558,0.66144) (0.70192,0.68182) ;
        SINK BOX 5I4 ;
      ENDSEG ;

      ARROWSEG 21 ;
        SOURCE BRANCH 23 ;
        PATH (0.33173,0.92476) (0.23558,0.92476) (0.23558,0.32132) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Детоксикация"' ;
        LABEL COORDINATES (0.13942,0.62226) ;
        SQUIGGLE COORDINATES (0.19231,0.64890) (0.23558,0.66614) ;
        SINK BOX 1M1 ;
      ENDSEG ;

      ARROWSEG 23 ;
        SOURCE BRANCH 20 ;
        PATH (0.46635,0.92476) (0.33173,0.92476) ;
        SINK BRANCH 21 22 ;
      ENDSEG ;

      ARROWSEG 20 ;
        SOURCE BRANCH 2 ;
        PATH (0.57212,0.92476) (0.46635,0.92476) ;
        SINK BRANCH 23 24 ;
      ENDSEG ;

      ARROWSEG 25 ;
        SOURCE BRANCH 2 ;
        PATH (0.57212,0.92476) (0.84615,0.92476) (0.84615,0.57210) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Список показаний"' ;
        LABEL COORDINATES (0.87115,0.78840) ;
        SQUIGGLE COORDINATES (0.87115,0.78370) (0.84615,0.70533) ;
        SINK BOX 5M1 ;
      ENDSEG ;

      ARROWSEG 12 ;
        SOURCE BRANCH 10 ;
        PATH (0.13462,0.41536) (0.13462,0.25078) (0.17788,0.25078) ;
        SINK BOX 1I1 ;
      ENDSEG ;

      ARROWSEG 10 ;
        SOURCE BRANCH 4 ;
        PATH (0.13462,0.58777) (0.13462,0.41536) ;
        SINK BRANCH 12 13 ;
      ENDSEG ;

      ARROWSEG 11 ;
        SOURCE BRANCH 4 ;
        PATH (0.13462,0.58777) (0.13462,0.77586) (0.49038,0.77586) ;
        SINK BOX 4I1 ;
      ENDSEG ;

      ARROWSEG 22 ;
        SOURCE BRANCH 23 ;
        PATH (0.33173,0.92476) (0.33173,0.49373) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Коррекция"' ;
        LABEL COORDINATES (0.24327,0.62382) ;
        SQUIGGLE COORDINATES (0.27788,0.65047) (0.33173,0.67398) ;
        SINK BOX 2M1 ;
      ENDSEG ;

      ARROWSEG 1 ;
        SOURCE BORDER C1 (0.36058,0.02665) ;
        PATH (0.37019,0.03135) (0.37019,0.10972) ;
        SINK BRANCH 14 15 16 ;
      ENDSEG ;

      ARROWSEG 14 ;
        SOURCE BRANCH 1 ;
        PATH (0.37019,0.10972) (0.37019,0.33699) ;
        SINK BOX 2C1 ;
      ENDSEG ;

      ARROWSEG 24 ;
        SOURCE BRANCH 20 ;
        PATH (0.46635,0.92476) (0.46635,0.66614) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Симптоматическое<CR>лечение"
' ;
        LABEL COORDINATES (0.33846,0.81818) ;
        SQUIGGLE COORDINATES (0.39327,0.87304) (0.46635,0.88558) ;
        SINK BOX 3M1 ;
      ENDSEG ;

      ARROWSEG 18 ;
        SOURCE BRANCH 16 ;
        PATH (0.49519,0.10972) (0.49519,0.50940) ;
        LABEL '{LWI I 7 255 255 }Знания о<CR>терапии' ;
        LABEL COORDINATES (0.38269,0.04859) ;
        SINK BOX 3C1 ;
      ENDSEG ;

      ARROWSEG 19 ;
        SOURCE BRANCH 2 ;
        PATH (0.57212,0.92476) (0.57212,0.85423) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма<CR>"Антибактериальное<CR>лечение
"' ;
        LABEL COORDINATES (0.67788,0.86364) ;
        SQUIGGLE COORDINATES (0.67500,0.88715) (0.57212,0.87774) ;
        SINK BOX 4M1 ;
      ENDSEG ;

      ARROWSEG 2 ;
        SOURCE BORDER M1 (0.56250,0.98433) ;
        PATH (0.57212,0.96395) (0.57212,0.92476) ;
        LABEL '{LWI I 7 255 255 }Подпрограмма "Показания"' ;
        LABEL COORDINATES (0.57692,0.97179) ;
        SINK BRANCH 19 20 25 ;
      ENDSEG ;

    ENDDIAGRAM ;

    DIAGRAM GLOSSARY A0G ;
     GLOSSARY ;
      TERM 'Знания о терапии'
      'Сведения о показанных методах и оценки их эффективности' ;
      TERM 'Рекомендации'
      'Выработанные АИС рекомендации по лечению' ;
      TERM 'Программа'
      'Основная программа системы' ;
      TERM 'Данные о больном'
      'Совокупность сведений о больном (анамнез, клинические данные, результат
ы исследований)' ;
      TERM 'Сочетаемость методов'
      'Литературные и экспертные знания и опыт о сочетаемости методов лечения'
 ;
      TERM 'Противопоказания'
      'Список противопоказанных методов для данного набора нарушений, с указан
ием степени опасности' ;
      TERM 'Показания'
      'Список показаний с оценками эффективности методов для данного набора на
рушений' ;
      TERM 'Медицинские знания'
      '' ;
      TERM 'Подпрограмма "Отбор методов"'
      'Подпрограмма отбора наиболее эффективно компенсирующих нарушения и безо
пасных методов' ;
      TERM 'Подпрограмма "Противопоказания"'
      'Подпрограмма отбора противопоказанных данному больному методов лечения'
 ;
      TERM 'Подпрограмма "Показания"'
      'Подпрограмма отбора показанных данному больному методов лечения с указа
нием их эффективности' ;
      TERM 'Подпрограмма "Диагноз"'
      'Подпрограмма определения развернутого диагноза' ;
      TERM 'Диагноз'
      'Развернутый диагноз, включающий этиопричину, осложнения, сопутствующие 
заболевания и указывающий степени основных нарушений' ;
      TERM '"Наш больной"'
      'У больного есть нефро- или гепатопатия' ;
      TERM 'ОППН'
      '' ;
      TERM '"Не наш больной (1)"'
      'У данного больного нет острой почеченой или печеночной патологии' ;
      TERM '"Не наш больной (2)"'
      'У данного больного острая почеченая или печеночная патология вызвана не
 рассматриваемой в программе этиопричиной' ;
      TERM 'Симптомы ОППН'
      'Симптомы и признаки острой печеночно-почечной недостаточности' ;
      TERM 'Anamnesis morbi'
      'Совокупность сведений об анамнезе заболевания' ;
      TERM 'Состояние систем'
      'Состояние систем организма - совокупность сведений о больном (клиническ
ие данные, результаты исследований)' ;
      TERM 'Anamnesis vitae'
      'Совокупность сведений об анамнезе жизни' ;
      TERM 'Этиология'
      'Этиология острой почеченой и/или печеночной патологии' ;
      TERM 'Патогенез'
      'Патогенез заболевания - степени основных нарушений, осложнения' ;
      TERM 'Сопутствующие заболевания'
      'Список сопутствующих заболеваний' ;
      TERM 'Подпрограмма "Анамнез жизни"'
      'Подпрограмма ввода сведений о  сопутствующих заболеваниях и об особенно
стях течения болезни' ;
      TERM 'Подпрограмма "Патогенез"'
      'Подпрограмма определения степени основных нарушений, состояния систем о
рганизма, осложнений' ;
      TERM 'Подпрограмма "Наличие ОППН"'
      'Подпрограмма определения наличия ОППН у данного больного' ;
      TERM 'Подпрограмма "Этиология"'
      'Подпрограмма определения этиопричины заболевания' ;
      TERM 'Знания о противопоказаниях'
      'Сведения о противопоказаниях и степени опасности применения методов' ;
      TERM 'Подпрограмма "Детоксикация"'
      'Подпрограмма выбора показанных данному больному детоксикационных методо
в лечения' ;
      TERM 'Подпрограмма "Коррекция"'
      'Подпрограмма выбора показанных данному больному коррегирующих и стабили
зирующих методов лечения' ;
      TERM 'Подпрограмма "Симптоматическое лечение"'
      'Подпрограмма выбора показанных данному больному симптоматических методо
в лечения' ;
      TERM 'Подпрограмма "Антибактериальное лечение"'
      'Подпрограмма выбора показанных данному больному антибактериальных метод
ов' ;
      TERM 'Подпрограмма "Список показаний"'
      'Подпрограмма формирования списка показанных данному больному методов ле
чения с указанием их эффективности' ;
      TERM 'Детоксикационные методы'
      'Список показанных больному детоксикационных методов' ;
      TERM 'Корригирующие методы'
      'Список показанных данному больному корригирующих и стабилизирующих мето
дов' ;
      TERM 'Симптоматическое лечение'
      'Список показанных данному больному симптоматических методов лечения' ;
      TERM 'Антибактериальное лечение'
      'Список показанных данному больному методов антибактериального лечения' 
;
     ENDGLOSS ;
    ENDDIAGRAM ;
  ENDMODEL ;

ENDKIT ;
