erase *.bak
ren BORDER_L.HTM* border_l.html
ren BORDER_R.HTM* border_r.html
ren BORDER_L.GIF border_l.gif
ren BORDER_R.GIF border_r.gif
ren SPACE4.GIF space4.gif
ren MENU_0.HTM* menu_0.html
ren MENU_A.HTM* menu_a.html
ren MENU_B.HTM* menu_b.html
ren MENU_E.HTM* menu_e.html
ren MENU_K.HTM* menu_k.html
ren MENU_L.HTM* menu_l.html
ren MENU_P.HTM* menu_p.html
ren MENU_T.HTM* menu_t.html
ren MUSIC_0.HTM* music_0.html
ren MUSIC_A.HTM* music_a.html
ren MUSIC_B.HTM* music_b.html
ren MUSIC_E.HTM* music_e.html
ren MUSIC_L.HTM* music_l.html
ren MUSIC_P.HTM* music_p.html
ren MUSIC_T.HTM* music_t.html
ren MUSIC_K.HTM* music_k.html
ren PROLOG.HTM* prolog.html
ren ALL.HTM* all.html
ren PAGES.HTM* pages.html
ren LINKS.HTM* links.html
ren PICTURES.HTM* pictures.html
ren BINARIES.HTM* binaries.html
ren ERRORS.HTM* errors.html
ren KEYWORDS.HTM* keywords.html
ren LEGEND.HTM* legend.html
ren WELCOME.HTM* welcome.html
ren BAGA33_4.MID baga33_4.mid
rem ren TERMIN22.MID termin22.mid
ren ANITRAS.MID anitras.mid
rem ren SONAT_A1.MID sonat_a1.mid
ren ITSHOP.MID itshop.mid
